///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BannerImagesModelData {
/*
{
  "image_field": "https://ommyfitnessbuckett.s3.amazonaws.com/images/banners/IMG_5269.HEIC"
} 
*/

  String? imageField;

  BannerImagesModelData({
    this.imageField,
  });
  BannerImagesModelData.fromJson(Map<String, dynamic> json) {
    imageField = json['image_field']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image_field'] = imageField;
    return data;
  }
}

class BannerImagesModel {
/*
{
  "status": "success",
  "message": "Car Engines fetched successfully",
  "status_code": 200,
  "data": [
    {
      "image_field": "https://ommyfitnessbuckett.s3.amazonaws.com/images/banners/IMG_5269.HEIC"
    }
  ]
} 
*/

  String? status;
  String? message;
  int? statusCode;
  List<BannerImagesModelData?>? data;

  BannerImagesModel({
    this.status,
    this.message,
    this.statusCode,
    this.data,
  });
  BannerImagesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BannerImagesModelData>[];
      v.forEach((v) {
        arr0.add(BannerImagesModelData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['status_code'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
