///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PlansModelData {
/*
{
  "name": "Weekly",
  "price": "5000.00",
  "duration": 7
} 
*/

  String? name;
  String? price;
  int? duration;

  PlansModelData({
    this.name,
    this.price,
    this.duration,
  });
  PlansModelData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    price = json['price']?.toString();
    duration = json['duration']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['price'] = price;
    data['duration'] = duration;
    return data;
  }
}

class PlansModel {
/*
{
  "status": "success",
  "message": "plans fetched  successfully",
  "status_code": 200,
  "data": [
    {
      "name": "Weekly",
      "price": "5000.00",
      "duration": 7
    }
  ]
} 
*/

  String? status;
  String? message;
  int? statusCode;
  List<PlansModelData?>? data;

  PlansModel({
    this.status,
    this.message,
    this.statusCode,
    this.data,
  });
  PlansModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PlansModelData>[];
      v.forEach((v) {
        arr0.add(PlansModelData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['status_code'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
