///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserSubscriptionModelDataPlan {
/*
{
  "name": "Weekly",
  "price": "5000.00",
  "duration": 7
} 
*/

  String? name;
  String? price;
  int? duration;

  UserSubscriptionModelDataPlan({
    this.name,
    this.price,
    this.duration,
  });
  UserSubscriptionModelDataPlan.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    price = json['price']?.toString();
    duration = json['duration']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['price'] = price;
    data['duration'] = duration;
    return data;
  }
}

class UserSubscriptionModelData {
/*
{
  "user": 1,
  "plan": {
    "name": "Weekly",
    "price": "5000.00",
    "duration": 7
  },
  "start_date": "2023-06-06",
  "end_date": "2023-06-07",
  "is_active": false,
  "remaining_days": 0
} 
*/

  int? user;
  UserSubscriptionModelDataPlan? plan;
  String? startDate;
  String? endDate;
  bool? isActive;
  int? remainingDays;

  UserSubscriptionModelData({
    this.user,
    this.plan,
    this.startDate,
    this.endDate,
    this.isActive,
    this.remainingDays,
  });
  UserSubscriptionModelData.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toInt();
    plan = (json['plan'] != null)
        ? UserSubscriptionModelDataPlan.fromJson(json['plan'])
        : null;
    startDate = json['start_date']?.toString();
    endDate = json['end_date']?.toString();
    isActive = json['is_active'];
    remainingDays = json['remaining_days']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    if (plan != null) {
      data['plan'] = plan!.toJson();
    }
    data['start_date'] = startDate;
    data['end_date'] = endDate;
    data['is_active'] = isActive;
    data['remaining_days'] = remainingDays;
    return data;
  }
}

class UserSubscriptionModel {
/*
{
  "status": "success",
  "message": "Subscription fetched  successfully",
  "status_code": 200,
  "data": {
    "user": 1,
    "plan": {
      "name": "Weekly",
      "price": "5000.00",
      "duration": 7
    },
    "start_date": "2023-06-06",
    "end_date": "2023-06-07",
    "is_active": false,
    "remaining_days": 0
  }
} 
*/

  String? status;
  String? message;
  int? statusCode;
  UserSubscriptionModelData? data;

  UserSubscriptionModel({
    this.status,
    this.message,
    this.statusCode,
    this.data,
  });
  UserSubscriptionModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    data = (json['data'] != null)
        ? UserSubscriptionModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['status_code'] = statusCode;
    data['data'] = this.data!.toJson();
    return data;
  }
}
