///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideosModelData {
/*
{
  "id": 1,
  "title": "Jinsi ya kukuza Uume",
  "video_url": "https://youtu.be/XGqU4iH1T5E",
  "images": "https://ommyfitnessbuckett.s3.amazonaws.com/images/madini/Rectangle_1.png"
} 
*/

  int? id;
  String? title;
  String? videoUrl;
  String? images;

  VideosModelData({
    this.id,
    this.title,
    this.videoUrl,
    this.images,
  });
  VideosModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    videoUrl = json['video_url']?.toString();
    images = json['images']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['video_url'] = videoUrl;
    data['images'] = images;
    return data;
  }
}

class VideosModel {
/*
{
  "status": "success",
  "message": "Videos fetched successfully",
  "status_code": 200,
  "data": [
    {
      "id": 1,
      "title": "Jinsi ya kukuza Uume",
      "video_url": "https://youtu.be/XGqU4iH1T5E",
      "images": "https://ommyfitnessbuckett.s3.amazonaws.com/images/madini/Rectangle_1.png"
    }
  ]
} 
*/

  String? status;
  String? message;
  int? statusCode;
  List<VideosModelData?>? data;

  VideosModel({
    this.status,
    this.message,
    this.statusCode,
    this.data,
  });
  VideosModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <VideosModelData>[];
      v.forEach((v) {
        arr0.add(VideosModelData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['status_code'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
